# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json .
RUN npm install --ignore-scripts
COPY . .
RUN npm run build

FROM node:lts-alpine AS runner
WORKDIR /app
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./package.json
# We need dependencies at runtime for MCP server and markmap-cli
RUN npm install --production --ignore-scripts --no-bin-links

ENTRYPOINT ["node", "build/index.js"]
